package com.BillingInformation.BillingInformation.Model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "bill_items")
public class Items {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) // identity tell that our id should be autogenerated
	private int id;
	 @Column(name = "ItemName", nullable = false, length = 100)
	    private String itemName;
	    
	    @Column(name = "ItemCode")
	    private int itemCode;
	    
	    @Column(name = "Quantity")
	    private int quantity;
	    
	    @Column(name = "Price")
	    private long price;
	    
	    @Column(name = "Tax(GST)")
	    private int tax;
	    
	    @Column(name = "Total")
	    private long total;
	    
	    @Column(name = "Total+Taxes")
	    private long totalTaxes;
	
	// Getters and Setters 
	    public int getId() {
	    	return id;
	    }
	public String getItemName() {
		return itemName;
	}
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}
	public int getItemCode() {
		return itemCode;
	}
	public void setItemCode(int itemCode) {
		this.itemCode = itemCode;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public long getPrice() {
		return price;
	}
	public void setPrice(long price) {
		this.price = price;
	}
	public int getTax() {
		return tax;
	}
	public void setTax(int tax) {
		this.tax = tax;
	}
	public long getTotal() {
		return total;
	}
	public void setTotal(long total) {
		this.total = total;
	}
	public long getTotalTaxes() {
		return totalTaxes;
	}
	public void setTotalTaxes(long totalTaxes) {
		this.totalTaxes = totalTaxes;
	}
	
	
}
